name: Node ja App

on:
    push:
        branches: [ main, prod ]
    pull_request: 
        branches: [ main ]


jobs:

    prepare: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Extract Version
          run : |
            VERSION=$(jq -r .version package.json)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "version: \"$VERSION\"" > version.yaml
            ls -l

        - name:  Debuugung the extracted Version
          run: echo $VERSION

        - name: Upload Version artifact
          uses: actions/upload-artifact@v4
          with:
            name: version
            path: version.yaml

    build:
      runs-on: ubuntu-latest
      needs: prepare
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: version

        - name: Load version into enviroment
          run: |
            VERSION=$(grep 'version' version.yaml | cut -d'"' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Setup Nodejs
          uses: actions/setup-node@v4
          with:
            node-version: "20"
            cache: 'npm'

        - name: Install dep
          run: npm i

        - name: Package app artifact
          run: |
            ARTIFACT_NAME="nodeapp-${VERSION}-${GITHUB_SHA:0:7}.tgz"
            mkdir -p artifacts
            mkdir -p artifact-temp
            shopt -s extglob
            cp -r !(artifact-temp|artifacts|.git|.github) artifact-temp/
            tar -czf "artifacts/$ARTIFACT_NAME" -C artifact-temp .
            rm -rf artifact-temp
            ls -R artifacts

        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: app-build
            path: artifacts/
    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: version

            - name: Load version into enviroment
              run: |
               VERSION=$(grep 'version' version.yaml | cut -d'"' -f2)
               echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Debuugung the extracted Version
              run: echo $VERSION

            - name: Download artifact 
              uses: actions/download-artifact@v4
              with:
                name: app-build

            
            - name: Extract app artifact
              run: |
                mkdir -p app
                ARTIFACT=$(ls nodeapp-${VERSION}-*.tgz | tail -n -1)
                echo $ARTIFACT
                tar -xzf  "$ARTIFACT" -C app
              

               
            - name : Config AWS credintails
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}   
                
            - name: Login into AWS ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and push Image 
              uses: docker/build-push-action@v6 
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.AWS_ECR_URL }}/nodeapp:${{ env.VERSION }}
         
          
    promot:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/prod'
      outputs:
        latest_tag: ${{ steps.extract.outputs.latest_tag }}
        base_tag: ${{ steps.extract.outputs.base_tag }}
      steps:
        - name : Config AWS credintails
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }} 

        - name:  Login into AWS ecr
          uses: aws-actions/amazon-ecr-login@v2
        
        - name: Get latest image with test tag
          id: extract
          run: |
            LATEST_TAG=$(aws ecr describe-images \
              --repository-name nodeapp \
              --region eu-central-1 \
              --output json \
            | jq -r '
                .imageDetails[]
                | select(.imageTags != null)
                | select([.imageTags[] | contains("test")] | any)
                | {pushedAt: .imagePushedAt, tag: (.imageTags[] | select(contains("test")))}
              ' | jq -s 'sort_by(.pushedAt) | last.tag')

            LATEST_TAG=$(echo "$LATEST_TAG" | tr -d '"')
            echo "Latest tag = $LATEST_TAG"
            export BASE_TAG=$(echo "$LATEST_TAG" | cut -d'-' -f1 | tr -d '"')
            echo "BASE_TAG=$BASE_TAG"
            echo "Latest tag = $LATEST_TAG" >> $GITHUB_OUTPUT
            echo "BASE_TAG=$BASE_TAG" >> $GITHUB_OUTPUT

    push-promoted-image:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/prod'

      needs: promot
      steps:
      - name : Config AWS credintails
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name:  Login into AWS ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push promoted image
        run: |
          docker pull ${{ secrets.AWS_ECR_URL }}/nodeapp:: ${{ needs.promot.outputs.latest_tag }}
          docker tag ${{ secrets.AWS_ECR_URL }}/nodeapp:: ${{ needs.promot.outputs.latest_tag }} /
            ${{ secrets.AWS_ECR_URL }}/nodeapp:: ${{ needs.promot.outputs.base_tag }}
          docker push ${{ secrets.AWS_ECR_URL }}/nodeapp:: ${{ needs.promot.outputs.base_tag }}



    deploy:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/prod'

      needs:
        - promot
        - push-promoted-image
      steps:

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: version

        - name: Load version into enviroment
          run: |
            VERSION=$(grep 'version' version.yaml | cut -d'"' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
        - name: ssh to the server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_NAME }}
            key: ${{ secrets.KEY }}
            script: |
              echo "pull image"
              docker pull ${{ secrets.AWS_ECR_URL }}/nodeapp:${{ needs.promot.outputs.base_tag }}

              docker stop nodeapp 
              docker rm nodeapp
              docker run -dp 81:3000 --name nodeapp ${{ secrets.AWS_ECR_URL }}/nodeapp:${{ needs.promot.outputs.base_tag }}